Adicionei uma view que é o Faq
taissarodrigues/ADA_bemFacil pull request #10
Opened 2024-05-07 19:21 UTC by taissarodrigues

# Descreva suas mudanças

## Tipo de mudança
- [ ] Correção de bug (mudança que corrige um problema)
- [ x ] Nova funcionalidade (mudança que adiciona funcionalidade)

## Lista de verificação antes de solicitar uma revisão
- [ x] Realizei uma revisão do meu próprio código
- [ x] Meu código segue as diretrizes de estilo deste projeto
- [ x] Fiz mudanças correspondentes na documentação
- [ x] Minhas mudanças não geram novos avisos

2024-05-07 19:57 UTC, Vitor-costa-diniz commented
O chatbot vai ser uma outra feature, no caso um outro ícone da tabview, então dentro da pasta de features criar uma nova pasta pra conter as views, componentes dessa view, as models e a viewModel.
Essa ViewModel é onde vai ta as funções de lógica de controle desse chatbot, no caso a de resposta, de capturar resposta, e talvez alguma outra, como se fosse se conectar a algum serviço externo por exemplo.

2024-05-07 20:13 UTC, Vitor-costa-diniz requested changes

2024-05-07 20:13 UTC, Vitor-costa-diniz commented on bem-facil/bem-facil/Features/TelaInicio/View/ChatBot.swift
> +    @State var messages: [String] = ["Bem vindo ao Faq do +Ben"]
Essa messages vão ser as mensagens do bot e do usuário né ? Se sim, seria interessante essa ser uma das variáveis da view model

2024-05-07 20:13 UTC, Vitor-costa-diniz commented on bem-facil/bem-facil/Features/TelaInicio/View/ChatBot.swift
> +                    .foregroundColor(Color("azul"))
Ao invés de usar a cor assim, que tal usar assim:
```
private struct BaseColor {
    let azul = Color("azul")
    }
    
 enum ColorCase {
    case azul
    }
    
    extension Color {
    static func benUI(_ colorCase: ColorCase) -> Color {
        let baseColor = BaseColor()
        switch colorCase {
        case .azul:
            return azul }
    }
}
```

### Exemplo de uso:
```
Text("Teste")
        .foregroundColor(Color.benUI(.azul))
```


Desse jeito fica mais fácil a manutenção do código caso seja necessário a troca de cor, além de evitar erros na hora da escrita que poderiam acontecer quando fosse escrever a string

2024-05-07 20:13 UTC, Vitor-costa-diniz commented on bem-facil/bem-facil/Features/TelaInicio/View/ChatBot.swift
> +                    .foregroundColor(Color("azul"))
Além disso é interessante que a cor começo com a letra maiúscula, seguindo o padrão de nome no swift.

2024-05-07 20:13 UTC, Vitor-costa-diniz commented on bem-facil/bem-facil/Features/TelaInicio/View/BotResponse.swift
> +    ]
Tentar separar em uma model, exemplo:

```
struct Pergunta {
    let pattern: String
    let response: String
}
```
Ai nesse mesmo arquivo poderia ter uma constate com esses mocks que tu escreveu:
```
static let mockQuestions: [Pergunta] = [
              Aqui as perguntas
]
```

2024-05-08 13:14 UTC, taissarodrigues commented on bem-facil/bem-facil/Features/TelaInicio/View/BotResponse.swift
> +    ]
Fiz a mudança

2024-05-08 16:45 UTC, Vitor-costa-diniz commented on bem-facil/bem-facil/Features/TelaChat/ViewModel/TelaChatViewModel.swift
> +    }
Tinha dado certo mas o texto que a pessoa digitou so sumiu do textfield quando o bot enviava a resposta, pq eles estavam com o mesmo tempo de espera, no caso ambos estão dentro do DispatchQueue.

Uma solução para isso, eu acho, seria fazer assim:
```

     func sendMessage() {
         let temporaryMessage = messageText
         withAnimation {
             messages.append("[USER]" + messageText)
         }
         DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
             let response = getResponse(message: temporaryMessage)
                     self.messages.append(response)
                 }
          self.messageText = ""
     }
```

Acho que assim ele continua enviado a mensagem corretamente, e não fica mostrando por mais tempo a mensagem digita pelo usuário no textfield depois dele ter apertado no botão de enviar a mensagem.

2024-05-09 11:52 UTC, taissarodrigues commented on bem-facil/bem-facil/Features/TelaChat/ViewModel/TelaChatViewModel.swift
> +    }
Mudei

2024-05-09 12:06 UTC, Vitor-costa-diniz approved these changes

2024-05-09 12:07 UTC, merged